language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
    - '/home/travis/.cache/Cypress'

script:
  - yarn test

# safelist
branches:
  only:
    - master
    - development
    - /.*(hotfix|feature).*$/
